<?php
?><?php
include("db.inc.php");

$Dept = getDepartmentByName("Access Builds");
$DeptID = $Dept['departmentid'];

$cnt = 1;
$CompStatus = getTaskStatusByName("Completed");
$Tasks = getTasksByDepartment($DeptID, $CompStatus['id']);
$BOQLines = getBOQLineItems();
$BOQUnits = getBOQTaskUnits();
$BOQCats = getBOQCategories();
$Complexes = getComplexes();
$RowArr = array();
$GrandTotal = 0;
foreach($Tasks AS $TaskID => $Task)
{
	$RowArr[$cnt] = array();
	$BOQItems = getTaskBOQItems($TaskID);
	$Maint = getAccessBuildByTaskID($TaskID);
	$UnitID = $Maint['unitid'];
	$Unit = getComplexeUnitByUnitID($UnitID);
	$RowArr[$cnt]['Date'] = substr($Task['actual_start_date'], 0, 10);
	$RowArr[$cnt]['CustomerName'] = $Unit['firstname'] . " " . $Unit['lastname'];
	$RowArr[$cnt]['Address'] = $Unit['unitname'] . " " . $Complexes[$Unit['complexid']]['complexname'];
	$RowArr[$cnt]['Ref'] = $Maint['ticketnumber'];
	$RowArr[$cnt]['Fault'] = $Maint['faultdesc'];
	$RowArr[$cnt]['Solution'] = $Maint['solutiondesc'];
	$RowArr[$cnt]['Time'] = $Maint['timeonsite'];
	$Total = 0;
	foreach($BOQItems AS $LineID => $LineRec)
	{
		$Val = $BOQItems[$LineID]['completed'] * $BOQLines[$LineID]['defaultcost'];
		$Total += $Val;
	}
	$Total = $Total * VATCALC;
	$GrandTotal += $Total;
	$RowArr[$cnt]['Total'] = sprintf("R %0.2f", $Total);
	$RowArr[$cnt]['Notes'] = $Maint['maintnote'];
	$cnt++;
}

$FileName = 'AccessBuild.Summary.' . date("Ymd") . '.xlsx';
require_once('PHPExcel.php');
$styleThinBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THIN, 'color' => array('argb' => 'FF000000'),),),);
$styleThickBrownBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF993300'),),),);
$styleThickBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF000000'),),),);
$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator("Company");
$objPHPExcel->getProperties()->setLastModifiedBy("Company");
$objPHPExcel->getProperties()->setTitle("Access Build Summary");
$objPHPExcel->getProperties()->setSubject("Access Build Summary");
$objPHPExcel->getProperties()->setDescription("Access Build summary. Generated by Company");
$objPHPExcel->setActiveSheetIndex(0);
$objPHPActiveSheet = $objPHPExcel->getActiveSheet();
$objPHPPageSetup = $objPHPActiveSheet->getPageSetup();
$objPHPPageSetup->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPPageSetup->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
$objPHPActiveSheet->setTitle("Access Build Summary");
$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Metrofibre logo');
$objDrawing->setDescription('Metrofibre logo');
$objDrawing->setPath('images/metrofibre.png');
// $objDrawing->setWidth(100);
$objDrawing->setHeight(60);
$objDrawing->setCoordinates('B1');
$objDrawing->setWorksheet($objPHPActiveSheet);
$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Company logo');
$objDrawing->setDescription('Company logo');
$objDrawing->setPath('images/Logo.jpg');
// $objDrawing->setWidth(130);
$objDrawing->setHeight(60);
$objDrawing->setCoordinates('H1');
$objDrawing->setWorksheet($objPHPActiveSheet);
unset($objDrawing);

$objPHPActiveSheet->mergeCells('A4:J4');
$objPHPActiveSheet->getStyle('A4:J4')->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('A4')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
$objPHPActiveSheet->getStyle('A4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPActiveSheet->getStyle('A4')->getFont()->setSize(14);
$objPHPActiveSheet->getStyle('A4')->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('A4', 'Access Build Summary');
$objPHPActiveSheet->mergeCells('A5:B5');
$objPHPActiveSheet->getStyle('A5:B5')->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('A5:B5')->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('A5', 'Contractor:');
$objPHPActiveSheet->mergeCells('C5:D5');
$objPHPActiveSheet->getStyle('C5:D5')->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->setCellValue('C5', 'Company');
$objPHPActiveSheet->mergeCells('E5:F5');
$objPHPActiveSheet->getStyle('E5:F5')->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('E5:F5')->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('E5', 'Generated:');
$objPHPActiveSheet->getStyle('G5')->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->setCellValue('G5', date("d M Y"));
$objPHPActiveSheet->mergeCells('H5:J5');
$objPHPActiveSheet->getStyle('H5:J5')->applyFromArray($styleThinBlackBorderOutline);

$CurrRow = 7;
$objPHPActiveSheet->getColumnDimension('A')->setWidth('4');
$objPHPActiveSheet->getColumnDimension('B')->setWidth('10');
$objPHPActiveSheet->getColumnDimension('C')->setWidth('19');
$objPHPActiveSheet->getColumnDimension('D')->setWidth('19');
$objPHPActiveSheet->getColumnDimension('E')->setWidth('9');
$objPHPActiveSheet->getColumnDimension('F')->setWidth('18');
$objPHPActiveSheet->getColumnDimension('G')->setWidth('19');
$objPHPActiveSheet->getColumnDimension('H')->setWidth('6');
$objPHPActiveSheet->getColumnDimension('I')->setWidth('9');
$objPHPActiveSheet->getColumnDimension('J')->setWidth('18');
$objPHPActiveSheet->getStyle('A' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('B' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('C' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('D' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('E' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('F' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('G' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('H' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('I' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('J' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('A' . $CurrRow . ':J' . $CurrRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPActiveSheet->getStyle('A' . $CurrRow . ':J' . $CurrRow)->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('A' . $CurrRow, 'Nr');
$objPHPActiveSheet->setCellValue('B' . $CurrRow, 'Date');
$objPHPActiveSheet->setCellValue('C' . $CurrRow, 'Customer Name');
$objPHPActiveSheet->setCellValue('D' . $CurrRow, 'Address');
$objPHPActiveSheet->setCellValue('E' . $CurrRow, 'Ref');
$objPHPActiveSheet->setCellValue('F' . $CurrRow, 'Fault');
$objPHPActiveSheet->setCellValue('G' . $CurrRow, 'Solution');
$objPHPActiveSheet->setCellValue('H' . $CurrRow, 'Time');
$objPHPActiveSheet->setCellValue('I' . $CurrRow, 'Total');
$objPHPActiveSheet->setCellValue('J' . $CurrRow, 'Notes');
$CurrRow++;
foreach($RowArr AS $cnt => $Row)
{
	$objPHPActiveSheet->getStyle('A' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('B' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('C' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('D' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('E' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('F' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('G' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('H' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('I' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->getStyle('J' . $CurrRow)->applyFromArray($styleThinBlackBorderOutline);
	$objPHPActiveSheet->setCellValue('A' . $CurrRow, $cnt);
	$objPHPActiveSheet->setCellValue('B' . $CurrRow, $Row['Date']);
	$objPHPActiveSheet->setCellValue('C' . $CurrRow, $Row['CustomerName']);
	$objPHPActiveSheet->setCellValue('D' . $CurrRow, $Row['Address']);
	$objPHPActiveSheet->setCellValue('E' . $CurrRow, $Row['Ref']);
	$objPHPActiveSheet->setCellValue('F' . $CurrRow, $Row['Fault']);
	$objPHPActiveSheet->setCellValue('G' . $CurrRow, $Row['Solution']);
	$objPHPActiveSheet->setCellValue('H' . $CurrRow, $Row['Time']);
	$objPHPActiveSheet->setCellValue('I' . $CurrRow, $Row['Total']);
	$objPHPActiveSheet->setCellValue('J' . $CurrRow, $Row['Notes']);
	$CurrRow++;
}
$objPHPActiveSheet->getStyle('H' . $CurrRow)->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('H' . $CurrRow, "Total");
$objPHPActiveSheet->setCellValue('I' . $CurrRow, sprintf("R %0.2f", $GrandTotal));
$objPHPExcel->setActiveSheetIndex(0);
// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $FileName . '"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
$objPHPExcel->disconnectWorksheets(); // Disconnect before you unset to properly clear the memory
unset($objPHPExcel);
unset($objWriter);
?>