<?php
include_once("db.inc.php");
$TaskID = pebkac($_GET['t']);
$TypeID = pebkac($_GET['i']);
$Task = getTaskByID($TaskID);
$DeptID = $Task['department_id'];
$TaskFiles = getTaskFiles($TaskID);
$ChkGroups = getTaskCheckGroups($TypeID, $DeptID);
$Checks = getTaskChecksOnly();
$FileName = $Task['task_name'] . '.PhotoSheet.' . date("Ymd") . '.xlsx';
require_once('PHPExcel.php');
$styleThinBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THIN, 'color' => array('argb' => 'FF000000'),),),);
$styleThickBrownBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF993300'),),),);
$styleThickBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF000000'),),),);
$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator("Company");
$objPHPExcel->getProperties()->setLastModifiedBy("Company");
$objPHPExcel->getProperties()->setTitle($Task['task_name'] . " - Photo sheet");
$objPHPExcel->getProperties()->setSubject($Task['task_name'] . " - Photo sheet");
$objPHPExcel->getProperties()->setDescription("Photo sheet for " . $Task['task_name'] . ". Generated by Company");
$objPHPExcel->setActiveSheetIndex(0);
$objPHPActiveSheet = $objPHPExcel->getActiveSheet();
$objPHPActiveSheet->setTitle(substr($Task['task_name'] . " - Photo sheet", 0, 31));
// $objPHPActiveSheet->getRowDimension(6)->setRowHeight(30);
$objPHPActiveSheet->mergeCells('A4:H4');
$objPHPActiveSheet->getStyle('A4')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
$objPHPActiveSheet->getStyle('A4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPActiveSheet->getStyle('A4')->getFont()->setSize(14);
$objPHPActiveSheet->getStyle('A4')->getFont()->setBold(true);
$objPHPActiveSheet->setCellValue('A4', $Task['task_name'] . " - Photo sheet");
$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Network logo');
$objDrawing->setDescription('Network logo');
$objDrawing->setPath('images/networklogo.png');
// $newSize = resizeImage($objDrawing->getWidth(), $objDrawing->getHeight(), 150, 70);
$objDrawing->setWidth(100);
$objDrawing->setHeight(60);
$objDrawing->setCoordinates('A1');
$objDrawing->setWorksheet($objPHPActiveSheet);
$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Company logo');
$objDrawing->setDescription('Company logo');
$objDrawing->setPath('images/Logo.jpg');
// $newSize = resizeImage($objDrawing->getWidth(), $objDrawing->getHeight(), 150, 70);
$objDrawing->setWidth(120);
$objDrawing->setHeight(60);
$objDrawing->setCoordinates('F1');
$objDrawing->setWorksheet($objPHPActiveSheet);
unset($objDrawing);
$Row = 5;
$Cnt = 0;
foreach($TaskFiles AS $FileID => $FileRec)
{
	if(($FileRec['type_id'] == $TypeID) && ($FileRec['batch'] == 0))
	{
		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$CheckName = (isset($Checks[$FileRec['check_id']])) ? $Checks[$FileRec['check_id']]['check_name'] : "-";
		$objDrawing->setName($CheckName . "_" . $FileID);
		$objDrawing->setDescription($CheckName . "_" . $FileID);
		$objDrawing->setPath($FileRec['filepath']);
		$objDrawing->setWidth(360);
		$objDrawing->setHeight(180);
		$Cell = 'A';
		if($Cnt == 1)
			$Cell = 'E';
		$objDrawing->setCoordinates($Cell . $Row);
		$objDrawing->setWorksheet($objPHPActiveSheet);
		$objPHPActiveSheet->setCellValue($Cell . ($Row + 9), $CheckName);
		$Cnt = !$Cnt;
		if($Cnt == 0)
		{
			$Row += 10;
		}
		unset($objDrawing);
	}
}
$objPHPExcel->setActiveSheetIndex(0);
// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $FileName . '"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
$objPHPExcel->disconnectWorksheets(); // Disconnect before you unset to properly clear the memory
unset($objPHPExcel);
unset($objWriter);
?>
